name: Publish Package

name: Publish Package

on:
  push:
    tags:
      - "release-*"
  workflow_dispatch:
    # allow manual trigger

jobs:
  build:
    permissions:
      contents: read
      packages: read
    uses: ExtractIntoVoid/workflows/.github/workflows/package.yml@main
    with:
      ProjName: EIV_Coroutines
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}